name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  SCHEME: "<#TITLE#>"

jobs:
  Swift:
    runs-on: macos-latest
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5"
      - uses: actions/checkout@v3
      - name: Build and test (Swift)
        run: swift test

  iOS:
    runs-on: macos-latest
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5"
      - uses: actions/checkout@v3
      - name: Build and test ( iOS)
        run: xcodebuild test -scheme "$SCHEME" -destination "platform=iOS Simulator,OS=16.0,name=iPhone SE (3rd generation)"

  macOS:
    runs-on: macos-latest
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5"
      - uses: actions/checkout@v3
      - name: Build and test ( macOS)
        run: xcodebuild test -scheme "$SCHEME" -destination "platform=macOS,arch=x86_64"
