name: <#TITLE#>

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  SCHEME: "<#TITLE#>"

jobs:
  Swift:
    runs-on: macos-latest
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5"
      - uses: actions/checkout@v3
      - name: Build and test (Swift)
        run: swift test
